name: Update Changelog

on:
  push:
    branches:
      - main
      
jobs:
  changeset:
    name: Changeset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: yarn

      - name: Generate changeset
        run: yarn changeset-version

      - name: Atualizando branch no github  
        env: 
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Branch is ... ${BRANCH}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update changelog"
          git push origin $BRANCH
          echo "Push with success"